### ISSUE TITLE
Not working with react 18 and next js 12 getting element ref

### ISSUE THREAD

**Issue by rishabhtatia1** [xobotyi/react-scrollbars-custom#234]
**What is the current behavior?**

**Steps to reproduce it and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have extra dependencies other than `react-scrollbars-custom`. Paste the link to your [JSFiddle](https://jsfiddle.net) or [CodeSandbox](https://codesandbox.io) example below:**

**What is the expected behavior?**

**A little about versions:**  
- _OS_: 
- _Browser (vendor and version)_: 
- _React_: 
- _`react-scrollbars-custom`_: 
- _Did this worked in the previous package version?_

**Comment by victorst79** [comment]
Same error here.

**Comment by proteye** [comment]
I have same error. Please, fix it!

**Comment by egoarka** [comment]
This issue happens due to `React.StrictMode`. Temporary fix is to disable it.

**Comment by GorlikItsMe** [comment]
I have same issue. For me helped change `reactStrictMode` to `false` in `next.config.js`, but this should be fixed in different way.

Error:
```
Error: Element was not created. Possibly you haven't provided HTMLDivElement to renderer's `elementRef` function.
```
https://github.com/xobotyi/react-scrollbars-custom/blob/6f9e391f30e191f20cf7603201ce7664e12dde01/src/ScrollbarTrack.tsx#L22-L30

**Comment by victorst79** [comment]
The latest release in the repository is from 2018 and the latest code push is from 2021 I think this repository is unmaintained. 
To solve these problems use another library: [`react-custom-scrollbars-2` ](https://www.npmjs.com/package/react-custom-scrollbars-2)
It is practically the same but you have to change the name of some parameters and it seems to have more maintenance and updates.

**Comment by xobotyi** [comment]
I'm trying to cut the time to rework the package atm

**Comment by Hikikomori** [comment]
Any updates on this issue ? Still presents on the latest release
@xobotyi

**Comment by petertodorov** [comment]
Wondering if any updates that may fix the issue are upcoming?
@xobotyi

**Comment by dvakatsiienko** [comment]
facing this problem as well

**Comment by nop33** [comment]
Facing the same issue...

**Comment by hmidmrii** [comment]
same here

**Comment by AnnaLynxy** [comment]
I'm sorry, any updates? @xobotyi

**Comment by idosius** [comment]
Plus one, also reproduced this, albeit without Next.js, rather with a client side application using React 18 and Vite 5.1

**Comment by vishnuur** [comment]
Same here, with react 18 and Vite 5.1. Any updates on this issue ?

**Comment by DarlingUUi** [comment]
I've got same issue in react 18. please let me know how to fix it.

**Comment by davidgolden** [comment]
FWIW the error is not thrown in strict mode in react 19
