### ISSUE TITLE
Native scroll bars become  visible when zoomed out

### ISSUE THREAD

**Issue by hanvyj** [xobotyi/react-scrollbars-custom#57]
I noticed some ugly white lines in my dark-themed app. (Tested in chrome Version 73.0.3683.86) Seemed the scroll bars were poking into the components, not being fully hidden by the padding. I edited my styles to add a few pixels of padding - but they seemed to appear randomly.

Just realized why. The scroll bars, in chrome at least, are sized independent to the web page's zoom field. This means the 17px of padding to hide the native scroll bars only works on 100%. If you zoom out, the 17px scales, but the scroll bars don't.

You can reproduce it on the Demo page by zooming out a little:

![image](https://user-images.githubusercontent.com/20140222/57297116-a7a5b080-70c6-11e9-9c7e-f6818d6245c7.png)

It's not much of an issue if you've got a pale background as they blend in until zoom levels that are just silly. But in dark apps (probably a major reason for styling scroll bars to begin with!) even a tiny bit of the scroll bar sticks out like a sore thumb.

Not sure if the 17px could be converted to a zoom-independent CSS unit?

**Comment by xobotyi** [comment]
Sad stuff but fast googling said that browser vendors are trying to hide zoom status from developers, so there is no working multi-browser solution =\
I'll try to do my best, but looks like it'll be a tough one.

**Comment by rvillalba-novetta** [comment]
Thought I'd give my two cents since it may work for some. I did not encounter the issue with IE or Edge and to work around Chrome and Firefox I was able to add the following styles to the Content component:

`  content: {
    scrollbarWidth: 0,
    '&::-webkit-scrollbar': {
      width: 0,
    },
  },`

**Comment by xobotyi** [comment]
actually the solution is on horizont =0
when i'll finish [this one](https://github.com/xobotyi/zoom-level) i'll solve that problem

**Comment by xobotyi** [comment]
BTW as i figured out - it happens only untill the page reload, if to zoom out and reload page - scrollbars will become invisible again =\

**Comment by tim-soft** [comment]
`ReferenceError: window is not defined`

@xobotyi current fix breaks SSR

**Comment by xobotyi** [comment]
@tim-soft yikes!
Should be fixed width v4.0.5

**Comment by rvillalba-novetta** [comment]
Was this ever fixed? I'm still using my work around and I haven't had any issues. Is there some problem I missed?

**Comment by xobotyi** [comment]
@rvillalba-novetta As you may notice - yes, 1.5 months ago, since v4.0.2 =)
Your workarond is not usable due to it's experimental stage and not suitable for IE/Edge.

**Comment by rvillalba-novetta** [comment]
@xobotyi I completely understand. I asked because I just updated to the latest version and still see it happening prominently within my use case for some reason. I also noticed it on the demo page although the effect is very subtle there. I'm not sure what may be different in my setup.

![image](https://user-images.githubusercontent.com/31288097/61373245-4db02c80-a867-11e9-9ab4-27bb3f2f3d36.png)

**Comment by xobotyi** [comment]
@rvillalba-novetta Yup, now i see.
Fix will be realeased in 1 hour i suppose.

**Comment by xobotyi** [comment]
@rvillalba-novetta tough stuff..
The bad thing about zoom - whole pixel layour is messed. These lines happent beacause of rounding operation and if you try to resize the window they'll show and hide periodically.
Tried to find anyhow uniform siluton but it seems there is none. So i'm just adding one extra margin pixel for zoom level !==1, to ensure the rounding wont show native traks..

**Comment by rvillalba-novetta** [comment]
No worries its a small corner case and I was unable to reproduce the issue on code sandbox so it seems to be working well in the general case. Not sure what about my setup may be causing my issues, but I'm able to work around them like before.
